version: '3.7'

services:
  db:
    image: kartoza/postgis:12.1
    container_name: db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=cfns_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - djangonetwork

  web:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
 djangonetwork:
     driver: bridge

volumes:
  postgres_data:

# docker-compose up
# DELETE ALL: docker system prune -a --volumes

# docker-compose up -d
# docker exec -it web python manage.py migrate
# docker exec -it web python manage.py createsuperuser