# Generated by Django 3.2 on 2021-08-09 19:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aisEncodedModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_from', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Encoded AIS message',
                'verbose_name_plural': 'Encoded AIS messages',
            },
        ),
        migrations.CreateModel(
            name='dabModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.IntegerField(null=True)),
                ('message_type', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('ship_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'DAB message',
                'verbose_name_plural': 'DAB messages',
            },
        ),
        migrations.CreateModel(
            name='FontAwesomeIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='lorawanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('ack', models.IntegerField(blank=True, null=True, verbose_name='Acknowledgement')),
                ('msg', models.IntegerField(blank=True, null=True, verbose_name='Message')),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('hdop', models.IntegerField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LoRaWAN message',
                'verbose_name_plural': 'LoRaWAN messages',
            },
        ),
        migrations.CreateModel(
            name='aisDecodedModel',
            fields=[
                ('aisencodedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.aisencodedmodel')),
                ('mmsi', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Shipname')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('course', models.FloatField(blank=True, null=True, verbose_name='Course')),
                ('ack', models.IntegerField(blank=True, null=True, verbose_name='Acknowledgement')),
                ('msg', models.IntegerField(blank=True, null=True, verbose_name='Message')),
                ('rssi', models.IntegerField(blank=True, null=True, verbose_name='RSSI')),
            ],
            options={
                'verbose_name': 'Decoded AIS message',
                'verbose_name_plural': 'Decoded AIS messages',
            },
            bases=('core.aisencodedmodel',),
        ),
        migrations.CreateModel(
            name='geoPolygonModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font_awesome_iconcolor', models.CharField(max_length=256)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('dab', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dabmodel')),
                ('lorawan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lorawanmodel')),
                ('aisDecoded', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisdecodedmodel')),
            ],
            options={
                'verbose_name': 'Geo Polygon Message',
                'verbose_name_plural': 'Geo Polygon Messages',
            },
        ),
        migrations.CreateModel(
            name='geoPointModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font_awesome_iconcolor', models.CharField(max_length=256)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pivot')),
                ('dab', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dabmodel')),
                ('lorawan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lorawanmodel')),
                ('aisDecoded', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisdecodedmodel')),
            ],
            options={
                'verbose_name': 'Geo Point Message',
                'verbose_name_plural': 'Geo Point Messages',
            },
        ),
        migrations.CreateModel(
            name='geoCircleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('font_awesome_iconcolor', models.CharField(max_length=256)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pivot')),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dab', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dabmodel')),
                ('lorawan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lorawanmodel')),
                ('aisDecoded', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisdecodedmodel')),
            ],
            options={
                'verbose_name': 'Geo Circle Message',
                'verbose_name_plural': 'Geo Circle Messages',
            },
        ),
    ]
