# Generated by Django 3.2 on 2021-07-07 11:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aisDecodedModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mmsi', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Schipnaam')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Locatie')),
                ('course', models.FloatField(blank=True, null=True, verbose_name='Koers')),
            ],
            options={
                'verbose_name': 'Decoded AIS message',
                'verbose_name_plural': 'Decoded AIS messages',
            },
        ),
        migrations.CreateModel(
            name='aisEncodedModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_from', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Encoded AIS message',
                'verbose_name_plural': 'Encoded AIS messages',
            },
        ),
        migrations.CreateModel(
            name='dabModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(null=True)),
                ('message_type', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('ship_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'DAB message',
                'verbose_name_plural': 'DAB messages',
            },
        ),
        migrations.CreateModel(
            name='FontAwesomeIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='geoMessageModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('aisDecoded', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisdecodedmodel')),
                ('aisEncoded', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisencodedmodel')),
                ('dab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dabmodel')),
            ],
            options={
                'verbose_name': 'Geo notification',
                'verbose_name_plural': 'Geo notifications',
            },
        ),
        migrations.CreateModel(
            name='geoCircleModel',
            fields=[
                ('geomessagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.geomessagemodel')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pivot')),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.geomessagemodel',),
        ),
        migrations.CreateModel(
            name='geoPointModel',
            fields=[
                ('geomessagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.geomessagemodel')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pivot')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.geomessagemodel',),
        ),
        migrations.CreateModel(
            name='geoPolygonModel',
            fields=[
                ('geomessagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.geomessagemodel')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.geomessagemodel',),
        ),
        migrations.AddField(
            model_name='aisdecodedmodel',
            name='aisEncoded',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aisencodedmodel'),
        ),
    ]
