# Generated by Django 3.2 on 2021-08-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawangatewayconnectionmodel',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gatewaymodel'),
        ),
        migrations.AlterField(
            model_name='lorawangatewayconnectionmodel',
            name='lorawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lorawanmodel'),
        ),
    ]
