# Generated by Django 3.2 on 2021-08-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecodedPayloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.IntegerField(max_length=256)),
                ('hdop', models.DecimalField(decimal_places=2, max_digits=19)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=19)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='UplinkMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_id', models.CharField(max_length=256)),
                ('f_port', models.IntegerField(blank=True, null=True)),
                ('f_cnt', models.IntegerField(blank=True, null=True)),
                ('frm_payload', models.CharField(max_length=256)),
                ('decoded_payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.decodedpayloadmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('uplink_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.uplinkmessagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='lorawanmodel',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datamodel'),
        ),
    ]
