# Generated by Django 3.2 on 2021-08-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorawanmodel',
            name='gateways',
        ),
    ]
