# Generated by Django 3.2 on 2021-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210824_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decodedpayloadmodel',
            name='alt',
            field=models.IntegerField(),
        ),
    ]
