# Generated by Django 3.2 on 2021-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210825_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawanmodel',
            name='alt',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='lorawanmodel',
            name='hdop',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
    ]
