# Generated by Django 3.2 on 2021-08-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_decodedpayloadmodel_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lorawanmodel',
            name='data',
        ),
        migrations.RemoveField(
            model_name='lorawanmodel',
            name='geom',
        ),
    ]
