# Generated by Django 3.2 on 2021-06-24 16:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAB',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField()),
                ('message_type', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('ship_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'DAB message',
                'verbose_name_plural': 'DAB messages',
            },
        ),
        migrations.AlterModelOptions(
            name='ais',
            options={'verbose_name': 'Encoded AIS message', 'verbose_name_plural': 'Encoded AIS messages'},
        ),
        migrations.AddField(
            model_name='ais',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='aisDecoded',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mmsi', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('course', models.FloatField(null=True)),
                ('encodedAIS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.ais')),
            ],
            options={
                'verbose_name': 'Decoded AIS message',
                'verbose_name_plural': 'Decoded AIS messages',
            },
        ),
    ]
