# Generated by Django 3.2 on 2021-07-05 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISDecoded',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mmsi', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Achternaam')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Locatie')),
                ('course', models.FloatField(blank=True, null=True, verbose_name='Koers')),
            ],
            options={
                'verbose_name': 'Decoded AIS message',
                'verbose_name_plural': 'Decoded AIS messages',
            },
        ),
        migrations.CreateModel(
            name='DAB',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(null=True)),
                ('message_type', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('ship_id', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'DAB message',
                'verbose_name_plural': 'DAB messages',
            },
        ),
        migrations.CreateModel(
            name='geoNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Pivot')),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('rightuppercorner', models.CharField(blank=True, max_length=256, null=True)),
                ('rightdowncorner', models.CharField(blank=True, max_length=256, null=True)),
                ('leftdowncorner', models.CharField(blank=True, max_length=256, null=True)),
                ('leftupcorner', models.CharField(blank=True, max_length=256, null=True)),
                ('DABmessage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.dab')),
                ('aisDecoded', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.aisdecoded')),
            ],
            options={
                'verbose_name': 'Geo notification',
                'verbose_name_plural': 'Geo notifications',
            },
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        migrations.AlterModelOptions(
            name='ais',
            options={'verbose_name': 'Encoded AIS message', 'verbose_name_plural': 'Encoded AIS messages'},
        ),
        migrations.AddField(
            model_name='ais',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geonotification',
            name='aisEncoded',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.ais'),
        ),
        migrations.AddField(
            model_name='aisdecoded',
            name='encodedAIS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.ais'),
        ),
    ]
