# Generated by Django 3.2 on 2021-06-22 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210622_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
