# Generated by Django 3.2 on 2021-07-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210705_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisdecoded',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Schipnaam'),
        ),
    ]
