# Generated by Django 3.2 on 2021-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_ais_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisdecoded',
            name='MMSI',
            field=models.IntegerField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aisdecoded',
            name='course',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aisdecoded',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
