# Generated by Django 3.2 on 2021-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_aisdecoded_encodedais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dab',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
