# Generated by Django 3.2 on 2021-07-05 14:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_dab_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisdecoded',
            name='course',
            field=models.FloatField(blank=True, null=True, verbose_name='Koers'),
        ),
        migrations.AlterField(
            model_name='aisdecoded',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='aisdecoded',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Achternaam'),
        ),
    ]
