# Generated by Django 3.2 on 2021-06-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210622_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aisdecoded',
            old_name='MMSI',
            new_name='mmsi',
        ),
    ]
