# Generated by Django 3.2 on 2021-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_mmsi_aisdecoded_mmsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAB',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField()),
                ('message_type', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('ship_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DAB message',
                'verbose_name_plural': 'DAB messages',
            },
        ),
    ]
